-- DarpaHubExample.lua
-- Universal premium example script for DarpaHubLib (v2.0.0-perfect)
-- Demonstrates full use of DarpaHub API: tabs, theme, plugins, scheduler, profiler, hooks, getgenv, FireHook, RenderStepped, CFrame, animated UI, notifications, safe visual tools and production-ready features.
-- IMPORTANT: This example intentionally avoids any gameplay-cheating features. All features are UI/visual/utility oriented and safe.
-- Author: DarpaHub Example Team
-- Date: Generated by ChatGPT assistant for user

-- CONFIG: change LIB_URL to your hosted DarpaHubLib.lua location if needed.
local LIB_URL = "https://raw.githubusercontent.com/oogaboogaman1231/DARPA-HUB/refs/heads/main/DarpaHubLib.lua" -- replace with your actual URL or let loader provide the lib

-- Try to acquire the DarpaHub library. If the loader already loaded it, reuse.
local DarpaHub = nil
local ok, res = pcall(function()
    if getgenv().DarpaHub then
        return getgenv().DarpaHub
    else
        local code = game:HttpGet and pcall(function() return game:HttpGet(LIB_URL) end) and game:HttpGet(LIB_URL) or nil
        if type(code) == "string" and #code > 10 then
            local chunk = loadstring(code)
            if chunk then
                local lib = chunk()
                return lib
            end
        end
    end
end)

DarpaHub = ok and res or (getgenv().DarpaHub or nil)

if not DarpaHub then
    warn("[DarpaHubExample] Failed to load DarpaHub library. Ensure LIB_URL is correct or the loader already injected the lib.")
    return
end

-- Initialize hub in unsupported sandbox mode (loader should call Init in real flow but we ensure it)
if not DarpaHub.State or not DarpaHub.State.Booted then
    pcall(function() DarpaHub:Init("unsupported") end)
end

-- Wait for UI subsystem to be ready (defensive)
local function waitUI()
    local attempts = 0
    while (not DarpaHub._private or not DarpaHub._private.UI or not DarpaHub._private.UI.Main) and attempts < 60 do
        task.wait(0.05)
        attempts = attempts + 1
    end
end
waitUI()

-- Helper short aliases and safety wrappers
local api = DarpaHub:GetSafeAPI()
local Theme = api.Theme
local Scheduler = api.Scheduler

local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer

-- Ensure some getgenv persistence slots
getgenv().DarpaHubExample = getgenv().DarpaHubExample or {}
local EX = getgenv().DarpaHubExample

-- Utility: nice print
local function info(...)
    print("[DarpaHubExample]", ...)
end

-- Create top-level tabs (Main, Visuals, Performance, Plugins, Tools, Settings)
local Tabs = {}
Tabs.Main = DarpaHub:CreateTab("Main")
Tabs.Visuals = DarpaHub:CreateTab("Visuals")
Tabs.Performance = DarpaHub:CreateTab("Performance")
Tabs.Plugins = DarpaHub:CreateTab("Plugins")
Tabs.Tools = DarpaHub:CreateTab("Tools")
Tabs.Settings = DarpaHub:CreateTab("Settings")

-- Activate Main tab by default
if Tabs.Main and Tabs.Main.Button then
    pcall(function() Tabs.Main.Button:MouseButton1Click() end)
end

-- ------------------------
-- Notification system (non-intrusive)
-- ------------------------
local Notifications = {}
Notifications._uid = 0
Notifications.Container = nil

local function ensureNotificationContainer()
    if Notifications.Container and Notifications.Container.Parent then return end
    local ui = DarpaHub._private.UI
    if not ui or not ui.Screen then return end
    local screen = ui.Screen
    local cont = Instance.new("Frame")
    cont.Name = "DH_Notifications"
    cont.Size = UDim2.new(0, 320, 0, 220)
    cont.Position = UDim2.new(1, -340, 0, 20)
    cont.AnchorPoint = Vector2.new(0,0)
    cont.BackgroundTransparency = 1
    cont.Parent = screen
    Notifications.Container = cont
end

local function notify(title, text, ttl)
    ttl = ttl or 4
    ensureNotificationContainer()
    if not Notifications.Container then return end
    Notifications._uid = Notifications._uid + 1
    local id = Notifications._uid

    local card = Instance.new("Frame")
    card.Name = "Notif_" .. id
    card.Size = UDim2.new(1, 0, 0, 64)
    card.Position = UDim2.new(0, 0, 0, ((id-1) * 72))
    card.BackgroundColor3 = Theme:GetColor("Primary")
    card.BorderSizePixel = 0
    card.Parent = Notifications.Container
    local corner = Instance.new("UICorner", card); corner.CornerRadius = UDim.new(0,8)

    local titleLabel = Instance.new("TextLabel", card)
    titleLabel.Size = UDim2.new(1, -12, 0, 22)
    titleLabel.Position = UDim2.new(0, 8, 0, 6)
    titleLabel.BackgroundTransparency = 1
    titleLabel.Font = Enum.Font.GothamBold
    titleLabel.TextSize = 14
    titleLabel.TextColor3 = Theme:GetColor("Text")
    titleLabel.Text = tostring(title)

    local bodyLabel = Instance.new("TextLabel", card)
    bodyLabel.Size = UDim2.new(1, -12, 0, 32)
    bodyLabel.Position = UDim2.new(0, 8, 0, 28)
    bodyLabel.BackgroundTransparency = 1
    bodyLabel.Font = Enum.Font.Gotham
    bodyLabel.TextSize = 12
    bodyLabel.TextColor3 = Theme:GetColor("Muted")
    bodyLabel.Text = tostring(text)
    bodyLabel.TextWrapped = true

    -- animate in
    card.Position = UDim2.new(1, 0, 0, 20 + ((id-1) * 72))
    card.AnchorPoint = Vector2.new(1,0)
    DarpaHub._private.Scheduler:AddJob(function()
        pcall(function()
            local t0 = tick()
            local duration = 0.28
            local startX = 340
            while tick() - t0 < duration do
                local alpha = (tick() - t0) / duration
                card.Position = UDim2.new(1, - (startX * alpha), 0, 20 + ((id-1) * 72))
                task.wait()
            end
            card.Position = UDim2.new(1, -6, 0, 20 + ((id-1) * 72))
        end)
    end, {persistent=false})

    -- schedule auto-remove
    spawn(function()
        task.wait(ttl)
        pcall(function()
            card:Destroy()
        end)
    end)

    return id
end

-- Expose notify in example API
EX.notify = notify

-- ------------------------
-- Hook examples: custom hooks and usage of FireHook/ConnectHook
-- ------------------------
DarpaHub:CreateHook("Example.CustomEvent")

-- listener that prints and shows notification
DarpaHub:ConnectHook("Example.CustomEvent", function(infoTbl)
    pcall(function()
        info("CustomEvent fired:", infoTbl and infoTbl.msg)
        notify("Hook", tostring(infoTbl and infoTbl.msg or "event fired"), 3)
    end)
end)

-- small function to demonstrate firing hooks (used as UI buttons)
local function fire_demo_hook()
    DarpaHub:FireHook("Example.CustomEvent", {msg = "Demo hook fired at " .. os.date("%X")})
end

-- ------------------------
-- Performance & profiler UI
-- ------------------------
local perfAPI = Tabs.Performance.API
perfAPI:AddLabel("Performance & Profiler")

local fpsLabel = perfAPI:AddLabel("FPS: calculating...")
local memLabel = perfAPI:AddLabel("Memory: calculating...")
local pingLabel = perfAPI:AddLabel("Ping: calculating...")
local profButton = perfAPI:AddButton("Toggle Profiler (5s samples)", function()
    local prof = DarpaHub._private.Profiler
    if not prof then notify("Profiler", "Profiler not ready", 3); return end
    if prof.enabled then
        prof:Disable(); notify("Profiler", "Profiler disabled", 2)
    else
        prof:Enable(); notify("Profiler", "Profiler enabled", 2)
    end
end)

-- Lightweight FPS/ping sampler
local lastTick = tick()
local frameCount = 0
local fps = 0
local function perf_tick(dt)
    frameCount = frameCount + 1
    if tick() - lastTick >= 1 then
        fps = math.floor(frameCount / (tick() - lastTick) + 0.5)
        frameCount = 0
        lastTick = tick()
        -- update labels
        pcall(function()
            fpsLabel.Text = "FPS: " .. tostring(fps)
            memLabel.Text = "Memory: " .. string.format("%.2f MB", collectgarbage("count")/1024)
            -- ping: estimate using Heartbeat (roundtrip to server internal) - use Player:GetNetworkPing if available
            local ping = 0
            if LocalPlayer and LocalPlayer:GetNetworkPing then
                ping = math.floor(LocalPlayer:GetNetworkPing() * 1000)
            end
            pingLabel.Text = "Ping: " .. tostring(ping) .. " ms"
        end)
    end
end

-- register perf job with scheduler
Scheduler:AddJob(function(dt) perf_tick(dt) end, {interval = nil, priority = 5})

-- ------------------------
-- Visual Tools Tab (camera helpers, cinematic camera, orbit, bloom UI)
-- ------------------------
local visAPI = Tabs.Visuals.API
visAPI:AddLabel("Camera & Visual Tools — safe, non-gameplay-affecting")

-- Camera orbit feature
DarpaHub:RegisterFeature("CameraOrbit", {
    DefaultEnabled = false,
    Priority = 40,
    Config = {
        Radius = 10,
        Speed = 0.6,
        Height = 2
    },
    Enable = function(selfFeature)
        notify("CameraOrbit", "Orbit enabled — press G to toggle", 3)
        selfFeature._active = true
        -- bind key for quick toggle
        DarpaHub:BindKey(Enum.KeyCode.G, function()
            DarpaHub:ToggleFeature("CameraOrbit")
        end)
    end,
    Disable = function(selfFeature)
        selfFeature._active = false
    end,
    Update = function(selfFeature)
        if not selfFeature._active then return end
        local cam = workspace and workspace.CurrentCamera
        local plr = Players.LocalPlayer
        if not cam or not plr or not plr.Character or not plr.Character:FindFirstChild("HumanoidRootPart") then return end
        local hrp = plr.Character.HumanoidRootPart
        local t = tick()
        local radius = selfFeature.Config.Radius or 6
        local height = selfFeature.Config.Height or 2
        local speed = selfFeature.Config.Speed or 0.5
        local targetPos = hrp.Position + Vector3.new(math.cos(t * speed) * radius, height, math.sin(t * speed) * radius)
        cam.CFrame = CFrame.new(cam.CFrame.Position:Lerp(targetPos, 0.12), hrp.Position)
    end
})

-- add UI controls for CameraOrbit
local orbitToggle = visAPI:AddToggle("Enable Camera Orbit (G)", false, function(state)
    if state then DarpaHub:EnableFeature("CameraOrbit") else DarpaHub:DisableFeature("CameraOrbit") end
end)
local orbitSpeed = visAPI:AddSlider("Orbit Speed", 0.05, 3, 0.6, function(v)
    local f = DarpaHub.Features["CameraOrbit"]
    if f then f.Config.Speed = v end
end)
local orbitRadius = visAPI:AddSlider("Orbit Radius", 2, 50, 10, function(v)
    local f = DarpaHub.Features["CameraOrbit"]
    if f then f.Config.Radius = v end
end)

-- Cinematic camera: smooth lerp towards desired offset behind player (safe)
DarpaHub:RegisterFeature("CinematicCamera", {
    DefaultEnabled = false,
    Priority = 30,
    Config = {
        Enabled = false,
        Distance = 8,
        Height = 2,
        Smooth = 0.14
    },
    Enable = function(selfFeature)
        selfFeature._active = true
        notify("CinematicCamera", "Cinematic camera enabled", 2)
    end,
    Disable = function(selfFeature)
        selfFeature._active = false
    end,
    Update = function(selfFeature)
        if not selfFeature._active then return end
        local cam = workspace.CurrentCamera
        local plr = Players.LocalPlayer
        if not cam or not plr or not plr.Character then return end
        local hrp = plr.Character:FindFirstChild("HumanoidRootPart")
        if not hrp then return end
        local desiredPos = hrp.Position - (hrp.CFrame.lookVector * (selfFeature.Config.Distance or 8)) + Vector3.new(0, (selfFeature.Config.Height or 2), 0)
        cam.CFrame = cam.CFrame:Lerp(CFrame.new(desiredPos, hrp.Position), selfFeature.Config.Smooth or 0.12)
    end
})

local cineToggle = visAPI:AddToggle("Enable Cinematic Camera", false, function(state)
    if state then DarpaHub:EnableFeature("CinematicCamera") else DarpaHub:DisableFeature("CinematicCamera") end
end)
visAPI:AddLabel("Cinematic settings below (change while enabled):")
local cineDist = visAPI:AddSlider("Distance", 2, 40, 8, function(v) local f = DarpaHub.Features["CinematicCamera"]; if f then f.Config.Distance = v end end)
local cineHeight = visAPI:AddSlider("Height", -2, 10, 2, function(v) local f = DarpaHub.Features["CinematicCamera"]; if f then f.Config.Height = v end end)

-- Visual overlay: dynamic vignette that pulses with Accent color
DarpaHub:RegisterFeature("VignettePulse", {
    DefaultEnabled = false,
    Priority = 110,
    Enable = function(selfFeature)
        selfFeature._ui = (function()
            local screen = DarpaHub._private.UI and DarpaHub._private.UI.Screen or nil
            if not screen then return nil end
            local img = Instance.new("ImageLabel")
            img.Name = "DH_Vignette"
            img.Size = UDim2.new(1,0,1,0)
            img.Position = UDim2.new(0,0,0,0)
            img.BackgroundTransparency = 1
            img.Image = "rbxassetid://0" -- keep empty/noisy image optional
            img.ZIndex = 9999
            img.Parent = screen
            img.ImageTransparency = 1
            pcall(function() img.ImageColor3 = Theme:GetColor("Accent") end)
            return img
        end)()
    end,
    Disable = function(selfFeature)
        if selfFeature._ui then pcall(function() selfFeature._ui:Destroy() end) end
        selfFeature._ui = nil
    end,
    Update = function(selfFeature)
        if not selfFeature._ui then return end
        local t = (math.sin(tick() / 1.2) + 1) / 2
        selfFeature._ui.ImageTransparency = 0.6 - (t * 0.25)
        -- subtle color pulse via tint
        local base = Theme:GetColor("Accent")
        local alt = Color3.new(1, 0.5, 0.6)
        local col = Color3.new(base.R + (alt.R - base.R) * t, base.G + (alt.G - base.G) * t, base.B + (alt.B - base.B) * t)
        pcall(function() selfFeature._ui.ImageColor3 = col end)
    end
})
local vpToggle = visAPI:AddToggle("Enable Vignette Pulse", false, function(s) if s then DarpaHub:EnableFeature("VignettePulse") else DarpaHub:DisableFeature("VignettePulse") end end)

-- ------------------------
-- Tools Tab - utilities (safe)
-- ------------------------
local toolsAPI = Tabs.Tools.API
toolsAPI:AddLabel("Utility tools — safe helpers")

-- Screenshot helper (uses Roblox Screenshot if available or simple GUI capture)
toolsAPI:AddButton("Take Screenshot (Gui-only)", function()
    local ui = DarpaHub._private.UI and DarpaHub._private.UI.Screen or DarpaHub._private.UI and DarpaHub._private.UI.ScreenGui
    if not ui then notify("Screenshot", "UI not available", 3); return end
    -- we'll snapshot the UI by temporarily drawing a frame and saving data via HttpService encode of properties (safe placeholder)
    notify("Screenshot", "Snapshotting UI (placeholder) - Save file manually in executor if desired.", 3)
    -- Note: real binary screenshot saving requires executor/host integration; we avoid dangerous calls here.
end)

-- Simple Auto-Respawn helper (non-cheat)
DarpaHub:RegisterFeature("AutoRespawnHelper", {
    DefaultEnabled = false,
    Priority = 90,
    Enable = function(selfFeature)
        selfFeature._active = true
        notify("AutoRespawn", "Auto-respawn enabled (safe).", 3)
    end,
    Disable = function(selfFeature)
        selfFeature._active = false
    end,
    Update = function(selfFeature)
        if not selfFeature._active then return end
        local plr = Players.LocalPlayer
        if not plr then return end
        local char = plr.Character
        if not char or (char and not char.Parent) then
            -- attempt to respawn safely
            pcall(function() plr:LoadCharacter() end)
        else
            -- check humanoid health
            local hum = char:FindFirstChildOfClass("Humanoid")
            if hum and hum.Health <= 0 then
                pcall(function() plr:LoadCharacter() end)
            end
        end
    end
})
toolsAPI:AddToggle("Enable Auto-Respawn Helper", false, function(s) if s then DarpaHub:EnableFeature("AutoRespawnHelper") else DarpaHub:DisableFeature("AutoRespawnHelper") end end)

-- ------------------------
-- Plugins Tab - demo plugin manifest + hot-reload UI
-- ------------------------
local pluginsAPI = Tabs.Plugins.API
pluginsAPI:AddLabel("Plugin manager (demo)")

-- Example plugin manifest (fake remote)
local demoPluginManifest = {
    name = "Demo.Visuals.Plugin",
    version = "0.0.1",
    url = "local", -- 'local' means we'll pass code in manifest.code
    author = "DarpaHubExample",
    description = "A demo plugin that registers a small visual widget and uses scheduler.",
    allowedAPIs = {"UI","Scheduler","Hooks","Persistence"},
    code = [[
        -- demo plugin code executed inside plugin sandbox (DarpaHub.Plugin)
        local API = DarpaHub
        API.Logger.Info("Demo plugin started")
        local tab = API.UI.CreateTab("DemoPlugin")
        local api = tab.API
        api:AddLabel("Demo plugin loaded")
        api:AddButton("Demo Action", function()
            API.Logger.Info("Demo Action triggered from plugin")
        end)
        -- schedule a simple heartbeat print
        local id = API.Scheduler.Add(function()
            API.Logger.Info("Plugin heartbeat")
        end, {interval=2, persistent=true})
        -- expose onUnload for clean-up
        function onUnload()
            API.Logger.Info("Demo plugin unloading")
            API.Scheduler.Remove(id)
        end
    ]]
}

DarpaHub:RegisterPluginManifest(demoPluginManifest)
pluginsAPI:AddButton("Load Demo Plugin", function()
    local ok, err = pcall(function()
        DarpaHub:LoadPlugin("Demo.Visuals.Plugin")
    end)
    if ok then notify("Plugin", "Demo plugin loaded", 2) else notify("Plugin", "Failed to load: "..tostring(err), 4) end
end)
pluginsAPI:AddButton("HotReload Demo Plugin", function()
    local ok, err = pcall(function() DarpaHub:HotReloadPlugin("Demo.Visuals.Plugin") end)
    if ok then notify("Plugin", "HotReload triggered", 2) else notify("Plugin", "HotReload failed: "..tostring(err), 4) end
end)
pluginsAPI:AddButton("Unload Demo Plugin", function()
    local ok = pcall(function() DarpaHub:UnloadPlugin("Demo.Visuals.Plugin") end)
    notify("Plugin", "Unload attempted", 2)
end)

-- ------------------------
-- Settings Tab - theme toggles, hotkeys, export/import config
-- ------------------------
local settingsAPI = Tabs.Settings.API
settingsAPI:AddLabel("Appearance & Settings")
settingsAPI:AddButton("Toggle Theme (Dark/Light)", function()
    local cur = DarpaHub._private.ActiveTheme and DarpaHub._private.ActiveTheme.Name or "Dark"
    if cur == "Dark" then DarpaHub.Theme:SetTheme("Light") else DarpaHub.Theme:SetTheme("Dark") end
    notify("Theme", "Switched theme to " .. (DarpaHub._private.ActiveTheme and DarpaHub._private.ActiveTheme.Name or "Unknown"), 2)
end)

settingsAPI:AddButton("Export Settings (to console)", function()
    local theme = DarpaHub._private.ActiveTheme and DarpaHub._private.ActiveTheme.Name or "None"
    print("[DarpaHubExample Export] Theme:", theme)
    notify("Export", "Exported settings to console", 2)
end)

settingsAPI:AddButton("HotReload Library (rebuild UI)", function()
    local ok, err = pcall(function() DarpaHub:HotReload() end)
    if ok then notify("HotReload", "Lib hot-reloaded", 2) else notify("HotReload", "HotReload failed: "..tostring(err), 4) end
end)

-- ------------------------
-- Profiler Viewer (in Main tab)
-- ------------------------
local mainAPI = Tabs.Main.API
mainAPI:AddLabel("DarpaHub Example — Main Dashboard")
mainAPI:AddButton("Fire demo hook", function() fire_demo_hook() end)
mainAPI:AddLabel("Profiler snapshot (check Output/or Profiler hook):")
mainAPI:AddButton("Print Profiler Stats", function()
    local prof = DarpaHub._private.Profiler
    if not prof then notify("Profiler", "Profiler not available", 3); return end
    local stats = prof:GetStats()
    for k,v in pairs(stats) do
        print(string.format("Profiler: %s -> calls=%d avg=%.6f last=%.6f", k, v.calls, (v.totalTime / math.max(1, v.calls)), v.lastTime))
    end
    notify("Profiler", "Profiler stats printed to console", 3)
end)

-- ------------------------
-- Example: FireHook scheduling demo and getgenv usage
-- ------------------------
-- schedule a repeating task that fires a hook every 10 seconds
local demoHookJob = Scheduler:AddJob(function()
    DarpaHub:FireHook("Example.CustomEvent", {msg = "Scheduled hook tick at " .. os.date("%X")})
end, {interval = 10, priority = 90, persistent = true})

-- store job id in getgenv for dev convenience
EX.demoHookJob = demoHookJob

-- ------------------------
-- Advanced: RenderStepped driven decorative effect (safe)
-- uses RenderStepped and CFrame but does NOT alter gameplay objects.
-- ------------------------
do
    local sparkle = {}
    sparkle.Enabled = false
    sparkle.Parts = {}
    sparkle.Radius = 4
    sparkle.Speed = 1.1
    sparkle.Count = 6

    function sparkle:Enable()
        if self.Enabled then return end
        self.Enabled = true
        -- create decorative attachments near camera (UI adornment style)
        local cam = workspace.CurrentCamera
        if not cam then return end
        for i = 1, self.Count do
            local p = Instance.new("Part")
            p.Name = "DH_Spark_" .. i
            p.Anchored = true
            p.CanCollide = false
            p.Size = Vector3.new(0.2,0.2,0.2)
            p.Transparency = 0.25
            p.Material = Enum.Material.Neon
            p.Color = Theme:GetColor("Accent")
            p.Parent = workspace
            table.insert(self.Parts, p)
        end
    end

    function sparkle:Disable()
        self.Enabled = false
        for _,p in ipairs(self.Parts) do
            p:Destroy()
        end
        self.Parts = {}
    end

    function sparkle:Update(dt)
        if not self.Enabled then return end
        local cam = workspace.CurrentCamera
        if not cam then return end
        local t = tick() * self.Speed
        for i,p in ipairs(self.Parts) do
            local angle = (i / #self.Parts) * math.pi * 2 + t
            local localPos = cam.CFrame.Position + (cam.CFrame.LookVector * 2) + Vector3.new(math.cos(angle) * self.Radius, math.sin(angle) * (self.Radius * 0.35), 0)
            p.CFrame = CFrame.new(localPos)
            -- color pulse
            local alpha = (math.sin(t + i) + 1) / 2
            p.Color = Color3.new(Theme:GetColor("Accent").R * (0.6 + 0.4 * alpha), Theme:GetColor("Accent").G * (0.6 + 0.4 * alpha), Theme:GetColor("Accent").B * (0.6 + 0.4 * alpha))
        end
    end

    -- register as a feature (safe visual)
    DarpaHub:RegisterFeature("SparkleDecor", {
        DefaultEnabled = false,
        Priority = 70,
        Enable = function(selfFeature)
            selfFeature._spark = sparkle
            selfFeature._spark:Enable()
        end,
        Disable = function(selfFeature)
            if selfFeature._spark then selfFeature._spark:Disable() end
        end,
        Update = function(selfFeature)
            if selfFeature._spark then selfFeature._spark:Update(task.wait()) end
        end
    })

    toolsAPI:AddToggle("Toggle Sparkle Decor", false, function(s) if s then DarpaHub:EnableFeature("SparkleDecor") else DarpaHub:DisableFeature("SparkleDecor") end end)
end

-- ------------------------
-- Friendly developer console commands (in-game bindings)
-- ------------------------
DarpaHub:BindKey(Enum.KeyCode.F1, function()
    notify("Dev", "F1 pressed - printing hub state", 3)
    print("DarpaHub State Dump:")
    print("Version:", DarpaHub.VERSION)
    print("Booted:", tostring(DarpaHub.State.Booted))
    print("Mode:", tostring(DarpaHub.State.Mode))
    print("Features Registered:", table.concat((function()
        local t = {}
        for k,_ in pairs(DarpaHub.Features) do table.insert(t,k) end
        return t
    end)(), ", "))
end)

-- ------------------------
-- Final: Cosmetic polish and startup messages
-- ------------------------
notify("DarpaHub Example", "Example loaded — use tabs to toggle features. Press RightControl to show/hide UI.", 4)
info("DarpaHub Example initialized. Version:", DarpaHub.VERSION)

-- Expose some helper fields so you can control from console:
EX.DarpaHub = DarpaHub
EX.Notify = notify
EX.Tabs = Tabs

-- End of Example file

